### ISSUE TITLE
Error in first step of CNS calling 

### ISSUE THREAD

**Issue by polchan** [baoxingsong/dCNS#29]
Dear Dr. Baoxing:
Hello! 
When I ran this command 
`python3 ~/tools/dCNS/scripts/extractInterGeneticSequence/sequenceUpStreamGeneAndDownStreamV2.py` use my data,
traceback message is this:

> Traceback (most recent call last):
  File "/ngsproject/bcguo/tools/dCNS/scripts/extractInterGeneticSequence/sequenceUpStreamGeneAndDownStreamV2.py", line 119, in <module>
    chromosome_gene_list1 = readGff(args.ref_gff)
  File "/ngsproject/bcguo/tools/dCNS/scripts/extractInterGeneticSequence/utils.py", line 210, in readGff
    g = Gene(gene_name, gene_strand[gene_name], gene_start[gene_name], gene_end[gene_name], chromosome_name)
KeyError: 'HF44677'

I think my gfffile have some error, but my attempt to solve it did not succeed.
can you help me?
thanks

**Comment by polchan** [comment]
sorry! 
One new error troubled me when I used `maskGenome`.
I want to mask my query genome,  but this error message warning me:

> terminate called after throwing an instance of 'std::out_of_range'
  what():  basic_string::replace: __pos (which is 29888) > this->size() (which is 0)

I have successfully masked 11 query genomes and reference genome, but 3 query genomes occurred this error. 
Really need your help! thanks
